### ISSUE TITLE
netbox_agent bails out with error on lshw

### ISSUE THREAD

**Issue by jczmok-iag** [Solvik/netbox-agent#116]
Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 11, in <module>
    load_entry_point('netbox-agent==0.5.1.dev3+gbb7c8c8.d20200216', 'console_scripts', 'netbox_agent')()
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8.d20200216-py3.7.egg/netbox_agent/cli.py", line 40, in main
    return run(config)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8.d20200216-py3.7.egg/netbox_agent/cli.py", line 35, in run
    server.netbox_update(config)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8.d20200216-py3.7.egg/netbox_agent/server.py", line 336, in netbox_update
    self.inventory = Inventory(server=self)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8.d20200216-py3.7.egg/netbox_agent/inventory.py", line 56, in __init__
    self.lshw = LSHW()
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8.d20200216-py3.7.egg/netbox_agent/lshw.py", line 18, in __init__
    self.hw_info = json.loads(data)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 25 column 8 (char 679)

i am using the master branch with the manual applied fixes from the "fix" branch

**Comment by jczmok-iag** [comment]
Package: lshw
Version: 02.18.85-0.1
Installed-Size: 763

**Comment by jczmok-iag** [comment]
lshw output according to script
[
{
  "id" : "SOMENAME",
  "class" : "system",
  "claimed" : true,
  "handle" : "DMI:0001",
  "description" : "Desktop Computer",
  "product" : "X9DRT-HF+ (To be filled by O.E.M.)",
  "vendor" : "Supermicro",
  "version" : "0123456789",
  "serial" : "0123456789",
  "width" : 64,
  "configuration" : {
    "boot" : "normal",
    "chassis" : "desktop",
    "family" : "To be filled by O.E.M.",
    "sku" : "To be filled by O.E.M.",
    "uuid" : "00000000-0000-0000-0000-AAAAAAAAAAA"
  },
  "capabilities" : {
    "smbios-2.7" : "SMBIOS version 2.7",
    "dmi-2.7" : "DMI version 2.7",
    "smp" : "Symmetric Multi-Processing",
    "vsyscall32" : "32-bit processes"
  }    {
      "id" : "core",
      "class" : "bus",
      "claimed" : true,
      "handle" : "DMI:0002",
      "description" : "Motherboard",
      "product" : "X9DRT-HF+",
      "vendor" : "Supermicro",

**Comment by jczmok-iag** [comment]
seems to be a lshw -json bug: when using JSONLint i get this:

Error: Parse error on line 24:
...-bit processes"		} {			"id": "core",	
----------------------^
Expecting 'EOF', '}', ',', ']', got '{

**Comment by jczmok-iag** [comment]
can't we do a scrap off the capabilities part before passing this to the json decoder ? we don't need this part

**Comment by Solvik** [comment]
what os/distro are you using ? 
I don't have the problem on Ubuntu 12.04 -> 18.04 and Debian 10

**Comment by jczmok-iag** [comment]
Found this:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929206

i have lots of servers, but this server is Debian 10 buster with lshw:

lshw:
  Installed:           02.18.85-0.3
  Candidate:        02.18.85-0.3
  Versionstabelle:
 *** 02.18.85-0.3 100
        100 /var/lib/dpkg/status
     02.18.85-0.1 500
        500 http://debian.inet.de/debian buster/main amd64 Packages

**Comment by jczmok-iag** [comment]
i did manually copy over lshw from another system where it works (debian9) - need to find the working version or just copy the file then i do a install script for the agent

**Comment by jczmok-iag** [comment]
issue fixed.
