### ISSUE TITLE
Better Supermicro Support (currently bails out)

### ISSUE THREAD

**Issue by jczmok-iag** [Solvik/netbox-agent#117]
Have a bailout now with the right lshw version.:

I attached the last lsow output as file

Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 11, in <module>
    load_entry_point('netbox-agent==0.5.1.dev3+gbb7c8c8.d20200216', 'console_scripts', 'netbox_agent')()
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8.d20200216-py3.7.egg/netbox_agent/cli.py", line 40, in main
    return run(config)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8.d20200216-py3.7.egg/netbox_agent/cli.py", line 35, in run
    server.netbox_update(config)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8.d20200216-py3.7.egg/netbox_agent/server.py", line 336, in netbox_update
    self.inventory = Inventory(server=self)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8.d20200216-py3.7.egg/netbox_agent/inventory.py", line 56, in __init__
    self.lshw = LSHW()
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8.d20200216-py3.7.egg/netbox_agent/lshw.py", line 48, in __init__
    self.find_cpus(j)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8.d20200216-py3.7.egg/netbox_agent/lshw.py", line 107, in find_cpus
    c["product"] = obj["product"]
KeyError: 'product'

**Comment by jczmok-iag** [comment]
[supermicro-lshw.txt](https://github.com/Solvik/netbox-agent/files/4211280/supermicro-lshw.txt)

**Comment by ThomasADavis** [comment]
Is this a dual-socket system with just one socket filled?

btw, you'll have problems with the serial numbers - you vendor (not supermicro) was supposed to populate that.
