### ISSUE TITLE
Supermicro Supermicro X9DRT-HF+

### ISSUE THREAD

**Issue by jczmok-iag** [Solvik/netbox-agent#119]
After getting the fixed code from #117 i still have issues but on other location. We definitely need more "catches" of errors.

This time the error is:
INFO:root:Creating RAID Card Supermicro SMC2108 (SN: FW-AD116BVAARBWA)
DEBUG:urllib3.connectionpool:http://XXXX:80 "GET /api/dcim/inventory-items/?device_id=2&tag=hw-disk HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:http://XXXX:80 "GET /api/dcim/manufacturers/?name=SMC2108 HTTP/1.1" 200 168
DEBUG:urllib3.connectionpool:http://XXXX:80 "POST /api/dcim/inventory-items/ HTTP/1.1" 201 453
INFO:root:Creating Disk SMC2108 003051452737b65c1a9072ab05b00506
DEBUG:urllib3.connectionpool:http://XXXX:80 "GET /api/dcim/manufacturers/?name= HTTP/1.1" 200 2269
Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 11, in <module>
    load_entry_point('netbox-agent==0.5.1.dev5+gdc4f90d.d20200221', 'console_scripts', 'netbox_agent')()
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev5+gdc4f90d.d20200221-py3.7.egg/netbox_agent/cli.py", line 40, in main
    return run(config)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev5+gdc4f90d.d20200221-py3.7.egg/netbox_agent/cli.py", line 35, in run
    server.netbox_update(config)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev5+gdc4f90d.d20200221-py3.7.egg/netbox_agent/server.py", line 337, in netbox_update
    self.inventory.update()
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev5+gdc4f90d.d20200221-py3.7.egg/netbox_agent/inventory.py", line 461, in update
    self.do_netbox_disks()
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev5+gdc4f90d.d20200221-py3.7.egg/netbox_agent/inventory.py", line 402, in do_netbox_disks
    self.create_netbox_disk(disk)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev5+gdc4f90d.d20200221-py3.7.egg/netbox_agent/inventory.py", line 351, in create_netbox_disk
    manufacturer = self.find_or_create_manufacturer(disk["Vendor"])
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev5+gdc4f90d.d20200221-py3.7.egg/netbox_agent/inventory.py", line 75, in find_or_create_manufacturer
    name=name,
  File "/usr/local/lib/python3.7/dist-packages/pynetbox-4.2.4-py3.7.egg/pynetbox/core/endpoint.py", line 142, in get
    "get() returned more than one result. "
ValueError: get() returned more than one result. Check that the kwarg(s) passed are valid for this endpoint or use filter() or all() instead.

Will check this script later on my X10 chassis. We also have X11 chassis, but havent tested there.

**Comment by Solvik** [comment]
hi @jczmok-iag 
Do you still have the issue with the recent netbox-agent versions?
