### ISSUE TITLE
KeyError: 'interface:type'

### ISSUE THREAD

**Issue by strus38** [Solvik/netbox-agent#141]
Hi

Running on virtualbox.

`Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/netbox_agent/cli.py", line 44, in main
    return run(config)
  File "/usr/local/lib/python3.6/dist-packages/netbox_agent/cli.py", line 39, in run
    server.netbox_create_or_update(config)
  File "/usr/local/lib/python3.6/dist-packages/netbox_agent/virtualmachine.py", line 76, in netbox_create_or_update
    self.network.create_or_update_netbox_network_cards()
  File "/usr/local/lib/python3.6/dist-packages/netbox_agent/network.py", line 399, in create_or_update_netbox_network_cards
    interface = self.create_netbox_nic(nic)
  File "/usr/local/lib/python3.6/dist-packages/netbox_agent/network.py", line 246, in create_netbox_nic
    type = self.get_netbox_type_for_nic(nic)
  File "/usr/local/lib/python3.6/dist-packages/netbox_agent/network.py", line 162, in get_netbox_type_for_nic
    return self.dcim_choices['interface:type']['Virtual']
KeyError: 'interface:type'`

**Comment by Solvik** [comment]
I'll test this today

**Comment by Solvik** [comment]
Hi @strus38 

I'll test this today

**Comment by strus38** [comment]
Any luck? ;-)

**Comment by Solvik** [comment]
I haven't been able to reproduce your issue. Which netbox version are you using ?

**Comment by strus38** [comment]
Netbox 2.2.6, let me upgrade and I come back to you.
Thanks!

**Comment by Solvik** [comment]
Oh, it's a very old version.
You have this error because in the latest release I've upgraded `netbox-agent` to be able to use the deprecation of the choice method (https://github.com/Solvik/netbox-agent/pull/127) that happened in 2.8 :)

**Comment by strus38** [comment]
Reinstalling the 2.8 as we speak. Thanks!

**Comment by strus38** [comment]
Works like a charm, except the 'tun0' interfaces ... But I skipped them for
now.
Thanks!

Le mer. 1 juil. 2020 à 19:56, Indigo Ping <indigoping4cgmi@gmail.com> a
écrit :

> Reinstalling the 2.8 as we speak. Thanks!
>

**Comment by Solvik** [comment]
I'd be happy to know why and fix it if necessary

**Comment by strus38** [comment]
Here is the error when those kind of interfacees are up:
```
8: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 172.18.134.0/32 brd 172.18.134.0 scope global tunl0
       valid_lft forever preferred_lft forever
```
```
DEBUG:urllib3.connectionpool:http://10.103.23.86:80 "GET /api/virtualization/interfaces/?mac_address=00%3A00%3A00%3A00&name=tunl0&virtual_machine_id=2 HTTP/1.1" 500 1791
Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/netbox_agent/cli.py", line 44, in main
    return run(config)
  File "/usr/local/lib/python3.6/dist-packages/netbox_agent/cli.py", line 39, in run
    server.netbox_create_or_update(config)
  File "/usr/local/lib/python3.6/dist-packages/netbox_agent/virtualmachine.py", line 76, in netbox_create_or_update
    self.network.create_or_update_netbox_network_cards()
  File "/usr/local/lib/python3.6/dist-packages/netbox_agent/network.py", line 394, in create_or_update_netbox_network_cards
    interface = self.get_netbox_network_card(nic)
  File "/usr/local/lib/python3.6/dist-packages/netbox_agent/network.py", line 151, in get_netbox_network_card
    **self.custom_arg_id,
  File "/usr/local/lib/python3.6/dist-packages/pynetbox/core/endpoint.py", line 139, in get
    filter_lookup = self.filter(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pynetbox/core/endpoint.py", line 227, in filter
    ret = [self._response_loader(i) for i in req.get()]
  File "/usr/local/lib/python3.6/dist-packages/pynetbox/core/query.py", line 350, in get
    return req_all()
  File "/usr/local/lib/python3.6/dist-packages/pynetbox/core/query.py", line 303, in req_all
    req = self._make_call(add_params=add_params)
  File "/usr/local/lib/python3.6/dist-packages/pynetbox/core/query.py", line 274, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 500 Internal Server Error but more specific details were not returned in json. Check the NetBox Logs or investigate this exception's error attribute.```

**Comment by Solvik** [comment]
Ok so there's in fact a buf for TUN interface on virtual machine

Interface's type with VM can only be virtual, we'll have to fix this
