### ISSUE TITLE
RaspeberryPi support - dmidecode crash

### ISSUE THREAD

**Issue by strus38** [Solvik/netbox-agent#144]
running netbox_agent on a rapsberry PI makes the program crash:

```
# netbox_agent -c nbagent.yaml --register
Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent/cli.py", line 44, in main
    return run(config)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent/cli.py", line 22, in run
    dmi = dmidecode.parse()
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent/dmidecode.py", line 74, in parse
    _data = _parse(buffer)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent/dmidecode.py", line 216, in _parse
    raise ParseError("Unable to parse 'dmidecode' output")
netbox_agent.dmidecode.ParseError: Unable to parse 'dmidecode' output

root@node05:/home/pi# dmidecode
# dmidecode 3.2
Scanning /dev/mem for entry point.
# No SMBIOS nor DMI entry point found, sorry.
```

where I guess we could use other info like:
```
$cat /proc/cpuinfo
...
$cat /proc/device-tree/model
Raspberry Pi 4 Model B Rev 1.1
$ inix -F

or even all usefull commands in there: https://raw.githubusercontent.com/raspberrypi/utils/master/raspinfo/raspinfo
```
Any way it could be supported in some way?
Thanks

**Comment by Solvik** [comment]
It seems that Raspberry doesn't have dmidecode infos and the agent relies heavily on dmidecode informations.

I have it on arm64 servers.

It'd mean special development for Raspberry PI. Would you be able propose a PR ? I don't have a rasp on hand

**Comment by strus38** [comment]
Yes, let me think about it, it could be nice.
Thanks
