### ISSUE TITLE
Netbox Datacenter: None

### ISSUE THREAD

**Issue by jczmok-iag** [Solvik/netbox-agent#154]
Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/netbox_agent/cli.py", line 44, in main
    return run(config)
  File "/usr/local/lib/python3.5/dist-packages/netbox_agent/cli.py", line 36, in run
    server.print_debug()
  File "/usr/local/lib/python3.5/dist-packages/netbox_agent/server.py", line 299, in print_debug
    print('Netbox Rack:', self.get_netbox_rack())
  File "/usr/local/lib/python3.5/dist-packages/netbox_agent/server.py", line 91, in get_netbox_rack
    site_id=self.get_netbox_datacenter().id,

please advise whats wrong here.
he finds out datacetner correctly
and the rack as well.

**Comment by Solvik** [comment]
do you still have the problem with the master branch?

**Comment by jczmok-iag** [comment]
i just installed this on a new node (with pip3 install..). it should be the master branch.

**Comment by jczmok-iag** [comment]
the full error message:

root@server-xx-xx:~# netbox_agent -c /etc/netbox_agent.yml --register --debug
Datacenter: SOMEDATACENTER
Netbox Datacenter: None
Rack: K3
Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/netbox_agent/cli.py", line 44, in main
    return run(config)
  File "/usr/local/lib/python3.5/dist-packages/netbox_agent/cli.py", line 36, in run
    server.print_debug()
  File "/usr/local/lib/python3.5/dist-packages/netbox_agent/server.py", line 299, in print_debug
    print('Netbox Rack:', self.get_netbox_rack())
  File "/usr/local/lib/python3.5/dist-packages/netbox_agent/server.py", line 91, in get_netbox_rack
    site_id=self.get_netbox_datacenter().id,
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by Solvik** [comment]
pip3 install doesn't install the master branch but the latest release

from what I understand, you don't have any datacenter which slugs equals `SOMEDATACENTER`
is that correct ?

**Comment by jczmok-iag** [comment]
Okay, so i use the latest release...

Regarding the data:
root@server-k3-05:~# more /etc/qualification 
DATACENTER: SOMEDATACENTER
RACK: K3
TENANT: provider

i didn't found a way to define netboxdatacenter

and i used the respective parts in netbox.yaml:


[config.yml.txt](https://github.com/Solvik/netbox-agent/files/4943630/config.yml.txt)

**Comment by Solvik** [comment]
the datacenter is found with a search based on the `slug` attribute in Netbox
is your datacenter's slug attribute `SOMEDATACENTER` ?

**Comment by jczmok-iag** [comment]
on /api/dcim/sites the slug is 'somedatacenter-ltd' and actually in /etc/qualification it is also lowercase.
strangely it does write uppercase "SOMEDATACENTER" and not "somedatacenter-ltd"

in the api : 
            "name": "Somedatacenter-ltd",
            "slug": "somedatacenter-ltd",


But where is the definition (or where do you setup the " Netbox Datacenter and Netbocx Rack" ?

**Comment by jczmok-iag** [comment]
Well. I sorted this out:  "| tr [a-z] [A-Z]" does lower to uppercase transformation. bad for slugs.
it kinda works, but when updating:

DEBUG:urllib3.connectionpool:http://netbox.xxxxx:80 "GET /api/dcim/sites/?slug=somedatacenter-ltd HTTP/1.1" 200 798
Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/netbox_agent/cli.py", line 44, in main
    return run(config)
  File "/usr/local/lib/python3.5/dist-packages/netbox_agent/cli.py", line 39, in run
    server.netbox_create_or_update(config)
  File "/usr/local/lib/python3.5/dist-packages/netbox_agent/server.py", line 287, in netbox_create_or_update
    ret, server = self.update_netbox_location(server)
  File "/usr/local/lib/python3.5/dist-packages/netbox_agent/server.py", line 72, in update_netbox_location
    if rack and server.rack and server.rack.id != nb_rack.id:
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by Solvik** [comment]
it's just a config example, but you're right I should change the example from uppercase to lowercase
In the master version, I've added more checks for location

it'd be better if you could test with it so you have a better error

thanks
