### ISSUE TITLE
Issue with interface

### ISSUE THREAD

**Issue by rosberen** [Solvik/netbox-agent#197]
INFO:root:Resetting tagged VLAN(s) on interface bond0.50
DEBUG:urllib3.connectionpool:http://netbox.local "GET /api/ipam/vlans/?vid=50 HTTP/1.1" 200 1161
Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/cli.py", line 44, in main
    return run(config)
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/cli.py", line 39, in run
    server.netbox_create_or_update(config)
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/server.py", line 292, in netbox_create_or_update
    self.network.create_or_update_netbox_network_cards()
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/network.py", line 412, in create_or_update_netbox_network_cards
    ret, interface = self.reset_vlan_on_interface(nic, interface)
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/network.py", line 227, in reset_vlan_on_interface
    nb_vlan = self.get_or_create_vlan(vlan_id)
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/network.py", line 194, in get_or_create_vlan
    vid=vlan_id,
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/endpoint.py", line 142, in get
    "get() returned more than one result. "
ValueError: get() returned more than one result. Check that the kwarg(s) passed are valid for this endpoint or use filter() or all() instead.

Netbox=3.0.9

**Comment by KivraChristoffer** [comment]
there is a other issue here about that. with a solution

**Comment by KivraChristoffer** [comment]
https://github.com/Solvik/netbox-agent/pull/195  is what we are using 
Netbox==3.1.14 now 
pynetbox==5.2.0

**Comment by cyrinux** [comment]
do you still reproduce this on the last version ?

**Comment by rosberen** [comment]
Yes

**Comment by rosberen** [comment]
EBUG:root:Updating Server...
DEBUG:root:Ignore interface lo
DEBUG:urllib3.connectionpool:http://172.28.8.35:8000 "OPTIONS /api/dcim/interfaces/ HTTP/1.1" 200 51127
DEBUG:urllib3.connectionpool:http://172.28.8.35:8000 "OPTIONS /api/ipam/ip-addresses/ HTTP/1.1" 200 9994
DEBUG:urllib3.connectionpool:http://172.28.8.35:8000 "GET /api/dcim/devices/?serial=CZ204701T0&limit=0 HTTP/1.1" 200 1262
DEBUG:root:Creating/Updating NIC...
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/cli.py", line 48, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/cli.py", line 44, in main
    return run(config)
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/cli.py", line 39, in run
    server.netbox_create_or_update(config)
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/server.py", line 362, in netbox_create_or_update
    self.network.create_or_update_netbox_network_cards()
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/network.py", line 378, in create_or_update_netbox_network_cards
    for nic in nb_nics[:]:
TypeError: 'RecordSet' object is not subscriptable

**Comment by rosberen** [comment]
Problem solved, everything works.
