### ISSUE TITLE
Problem adding interfaces

### ISSUE THREAD

**Issue by asanchov** [Solvik/netbox-agent#273]
When I run netbox_agent -c /etc/netbox-agent.yml --register, I get This:

DEBUG:root:It's a virtual machine
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): X.X.X.X:XXXX
DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "GET /api/virtualization/virtual-machines/?name=RockylinuxESXI HTTP/1.1" 200 695
DEBUG:root:Ignore interface lo
DEBUG:root:Ignore interface docker0
DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "OPTIONS /api/dcim/interfaces/ HTTP/1.1" 200 62889
DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "OPTIONS /api/ipam/ip-addresses/ HTTP/1.1" 200 10268
DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "GET /api/virtualization/virtual-machines/?name=RockylinuxESXI HTTP/1.1" 200 695
DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "OPTIONS /api/virtualization/interfaces/ HTTP/1.1" 200 14335
DEBUG:root:Creating/Updating NIC...
DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "GET /api/virtualization/interfaces/?virtual_machine_id=1 HTTP/1.1" 200 663
DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "GET /api/ipam/ip-addresses/?interface_id=1 HTTP/1.1" 400 82
Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/netbox_agent/cli.py", line 44, in main
    return run(config)
  File "/usr/local/lib/python3.9/site-packages/netbox_agent/cli.py", line 39, in run
    server.netbox_create_or_update(config)
  File "/usr/local/lib/python3.9/site-packages/netbox_agent/virtualmachine.py", line 104, in netbox_create_or_update
    self.network.create_or_update_netbox_network_cards()
  File "/usr/local/lib/python3.9/site-packages/netbox_agent/network.py", line 383, in create_or_update_netbox_network_cards
    netbox_ips = nb.ipam.ip_addresses.filter(
  File "/usr/local/lib/python3.9/site-packages/pynetbox/core/endpoint.py", line 225, in filter
    return response_loader(req.get(), self.return_obj, self)
  File "/usr/local/lib/python3.9/site-packages/pynetbox/core/query.py", line 352, in get
    return req_all()
  File "/usr/local/lib/python3.9/site-packages/pynetbox/core/query.py", line 303, in req_all
    req = self._make_call(add_params=add_params)
  File "/usr/local/lib/python3.9/site-packages/pynetbox/core/query.py", line 274, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'interface_id': ['Select a valid choice. 1 is not one of the available choices.']}

I'm stuck when adding the new interface, any help would be appreciated

Thanks

**Comment by asanchov** [comment]
> When I run netbox_agent -c /etc/netbox-agent.yml --register, I get This:
> 
> DEBUG:root:It's a virtual machine DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): X.X.X.X:XXXX DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "GET /api/virtualization/virtual-machines/?name=RockylinuxESXI HTTP/1.1" 200 695 DEBUG:root:Ignore interface lo DEBUG:root:Ignore interface docker0 DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "OPTIONS /api/dcim/interfaces/ HTTP/1.1" 200 62889 DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "OPTIONS /api/ipam/ip-addresses/ HTTP/1.1" 200 10268 DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "GET /api/virtualization/virtual-machines/?name=RockylinuxESXI HTTP/1.1" 200 695 DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "OPTIONS /api/virtualization/interfaces/ HTTP/1.1" 200 14335 DEBUG:root:Creating/Updating NIC... DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "GET /api/virtualization/interfaces/?virtual_machine_id=1 HTTP/1.1" 200 663 DEBUG:urllib3.connectionpool:http://X.X.X.X:XXXX "GET /api/ipam/ip-addresses/?interface_id=1 HTTP/1.1" 400 82 Traceback (most recent call last): File "/usr/local/bin/netbox_agent", line 8, in sys.exit(main()) File "/usr/local/lib/python3.9/site-packages/netbox_agent/cli.py", line 44, in main return run(config) File "/usr/local/lib/python3.9/site-packages/netbox_agent/cli.py", line 39, in run server.netbox_create_or_update(config) File "/usr/local/lib/python3.9/site-packages/netbox_agent/virtualmachine.py", line 104, in netbox_create_or_update self.network.create_or_update_netbox_network_cards() File "/usr/local/lib/python3.9/site-packages/netbox_agent/network.py", line 383, in create_or_update_netbox_network_cards netbox_ips = nb.ipam.ip_addresses.filter( File "/usr/local/lib/python3.9/site-packages/pynetbox/core/endpoint.py", line 225, in filter return response_loader(req.get(), self.return_obj, self) File "/usr/local/lib/python3.9/site-packages/pynetbox/core/query.py", line 352, in get return req_all() File "/usr/local/lib/python3.9/site-packages/pynetbox/core/query.py", line 303, in req_all req = self._make_call(add_params=add_params) File "/usr/local/lib/python3.9/site-packages/pynetbox/core/query.py", line 274, in _make_call raise RequestError(req) pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'interface_id': ['Select a valid choice. 1 is not one of the available choices.']}
> 
> I'm stuck when adding the new interface, any help would be appreciated
> 
> Thanks

Found the solution:
When  install via pip3 install netbox-agent the version is 0.6.2 not the last 0.7.1
