### ISSUE TITLE
FR: inventory for raspberry pi modules

### ISSUE THREAD

**Issue by nimbo78** [Solvik/netbox-agent#318]
Hi
We have plenty of Raspberry Pi CM4 modules on our network and want to inventory them in NetBox. However, when we start the NetBox agent:
`Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/netbox_agent/cli.py", line 50, in main
    return run(config)
  File "/usr/local/lib/python3.9/dist-packages/netbox_agent/cli.py", line 24, in run
    dmi = dmidecode.parse()
  File "/usr/local/lib/python3.9/dist-packages/netbox_agent/dmidecode.py", line 74, in parse
    _data = _parse(buffer)
  File "/usr/local/lib/python3.9/dist-packages/netbox_agent/dmidecode.py", line 216, in _parse
    raise ParseError("Unable to parse 'dmidecode' output")
netbox_agent.dmidecode.ParseError: Unable to parse 'dmidecode' output`

`> dmidecode
# dmidecode 3.3
# No SMBIOS nor DMI entry point found, sorry.
`

Is there any workaround for Pi's?

**Comment by CllaudiaB** [comment]
Hello @nimbo78 ,
Currently netbox-agent doesn't handle raspberry pi, we'll add this feature later.
