### ISSUE TITLE
Unhandled missing pvid in LLDP VLAN data

### ISSUE THREAD

**Issue by TiagoTT** [Solvik/netbox-agent#335]
Some servers only have tagged VLANs available and no un-tagged VLAN, so there is no `pvid` in the LLDP data, and we get the following error:
```
Traceback (most recent call last):
  File "/opt/netbox_agent_venv/bin/netbox_agent", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/netbox_agent_venv/lib/python3.13/site-packages/netbox_agent/cli.py", line 50, in main
    return run(config)
  File "/opt/netbox_agent_venv/lib/python3.13/site-packages/netbox_agent/cli.py", line 43, in run
    server.netbox_create_or_update(config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/opt/netbox_agent_venv/lib/python3.13/site-packages/netbox_agent/server.py", line 413, in netbox_create_or_update
    self.network.create_or_update_netbox_network_cards()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/netbox_agent_venv/lib/python3.13/site-packages/netbox_agent/network.py", line 448, in create_or_update_netbox_network_cards
    ret, interface = self.reset_vlan_on_interface(nic, interface)
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/netbox_agent_venv/lib/python3.13/site-packages/netbox_agent/network.py", line 250, in reset_vlan_on_interface
    pvid_vlan = [key for (key, value) in lldp_vlan.items() if value['pvid']]
                                                              ~~~~~^^^^^^^^
KeyError: 'pvid'
```

A proposed fix was submitted in https://github.com/Solvik/netbox-agent/pull/326 .

**Comment by ribetm** [comment]
Hello @TiagoTT  and thank you for your contributions !

We're currently adding CI tests, so we were waiting for them to release everything together
